{% set name = "pg8000" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c99108c630b1c468668a8def38be4c91b2fb7cf0154ce7918e7a3912e60652d7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scramp ==1.4.0

test:
  imports:
    - pg8000

about:
  home: https://github.com/tlocke/pg8000
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PostgreSQL interface library

  description: |
    pg8000 is a Pure-Python interface to the PostgreSQL database engine.  It is
    one of many PostgreSQL interfaces for the Python programming language.
    pg8000 is somewhat distinctive in that it is written entirely in Python and
    does not rely on any external libraries (such as a compiled python module,
    or PostgreSQL's libpq library). pg8000 supports the standard Python DB-API
    version 2.0.
    pg8000's name comes from the belief that it is probably about the 8000th
    PostgreSQL interface for Python.

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
